name = "MUSEData"
uuid = "a75d15a4-64f0-4121-831c-1d84b3651e55"
authors = ["Jarle Brinchmann"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
